cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'
urlpatterns = [
    path('', views.CvView.as_view(), name='cv_page'),
    path('cv_details/<int:pk>/', views.CvDetailsView.as_view(), name='cv_details'),
]

hoomanjafari/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='home')),
    path('cv/', include('cv.urls', namespace='cv')),
    path('about-us/', include('aboutus.urls', namespace='about-us')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('article/', include('article.urls', namespace='article')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/models.py
from django.db import models


class MyCv(models.Model):
    main_img = models.ImageField(upload_to='img/%y%m%d%H%M')
    title = models.CharField(max_length=300)
    body = models.CharField(max_length=300)
    details = models.TextField()
    customer = models.CharField(max_length=99)
    added_time = models.DateTimeField(auto_now_add=True)

    img_one = models.ImageField(upload_to='img/%y%m%d%H%M', null=True, blank=True)
    img_two = models.ImageField(upload_to='img/%y%m%d%H%M', null=True, blank=True)
    img_three = models.ImageField(upload_to='img/%y%m%d%H%M', null=True, blank=True)
    img_four = models.ImageField(upload_to='img/%y%m%d%H%M', null=True, blank=True)
    img_five = models.ImageField(upload_to='img/%y%m%d%H%M', null=True, blank=True)
    img_six = models.ImageField(upload_to='img/%y%m%d%H%M', null=True, blank=True)

    def __str__(self):
        return f'{self.body[:20]}'


class Hooman(models.Model):
    resume = models.FileField(upload_to='pdf/%y%m%d%H%M')

cv/views.py
from django.shortcuts import (render, get_object_or_404)
from django.views import View
from .models import MyCv


class CvView(View):
    def get(self, request):
        cv = MyCv.objects.all().order_by('-added_time')
        return render(request, 'cv/cv.html', {'cv': cv})


class CvDetailsView(View):
    def get(self, request, **kwargs):
        cv_selected = MyCv.objects.filter(pk=kwargs['pk'])
        return render(request, 'cv/cv_details.html', {
            'cv_selected': cv_selected
        })

cv/templates/cv/cv.html
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="برنامه نویسی سایت به صورت اختصاصی از صفر نا صد، حرفه ای، امنیت بالا، سرعت بالا">
    <link rel="icon" href="/static/images/web-icon.png" type="image/png">
    <link rel="stylesheet" href="/static/css/cv.css">
    <title>نمونه کار ها | برنامه نویسی وب</title>
</head>

<body>
    <div class="cv-app">
        {% include 'includes/navbar.html' %}
        <div class="cv-white-space"></div>
        <header class="cv-header">
            <div class="cv-header-content">
                <article class="cv-article">
                    <p class="cv-welcome-p">خوش آمدید</p>
                    <div class="cv-article-text">
                        <div class="cv-text-border"></div>
                        <p class="cv-article-p">
                            سلام به شمای عزیز که مشتاق هستی برخی از نمونه کار های من رو در این قسمت از وب سایت مشاهده کنید
                        </p>
                        <h1>
                            من با علاقه ی زیادی برنامه نویسی رو یاد گرفتم و سعی کردم در هنگام یادگیری درست اموزش ببینم تا پروژه های که انجام میدم از استاندارد های جهانی پیروی کنند پس در جریان باشین کیفیت در اولویت کار من هست
                        </h1>
                    </div>
                </article>
            </div>
        </header>

        <div class="cv-content">
            <h1 class="cv-content-p"><i class="fa fa-arrow-down"></i> نمونه کار ها</h1>
            {% for i in cv %}
            <a href="{% url 'cv:cv_details' pk=i.id %}">
                <div class="cv-item">
                    <div class="cv-item-img">
                        <img src="{{ i.main_img.url }}" class="">
                    </div>
                    <div class="cv-details">
                        <h1 class="cv-article-title">
                            {{ i.title }}
                        </h1>
                        <h1 class="cv-article-info">
                            {{ i.body }}
                        </h1>
                        <div class="cv-article-info-customer">
                            {{ i.customer }}
                        </div>
                    </div>
                    <p class="show-details">مشاهده جزئیات</p>
                </div>
            </a>
            {% endfor %}
        </div>

        {% include 'includes/footer.html' %}
    </div>

    <script src="/static/js/navbars.js"></script>
</body>

</html>

cv/templates/cv/cv_details.html
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="برنامه نویسی سایت به صورت اختصاصی از صفر نا صد، حرفه ای، امنیت بالا، سرعت بالا">
    <link rel="icon" href="/static/images/web-icon.png" type="image/png">
    <link rel="stylesheet" href="/static/css/cv_details.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <title>جزئیات نمونه کارها | برنامه نویسی وب</title>
</head>

<body>
    {% include 'includes/navbar.html' %}
    <div class="cv-details-white-space"></div>
    <main class="cv-details-main-container">
    {% for i in cv_selected %}
        <div class="cv-details-img">
            <h2>
                جزئیات نمونه کار
            </h2>
            <div class="swiper mySwiper">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper">
                    <!-- Slides -->
                    {% if i.img_one != '' %}
                    <div class="swiper-slide">
                        <div class="swiper-slide-item">
                            <img src="{{ i.img_one.url }}">
                        </div>
                    </div>
                    {% endif %}

                    {% if i.img_two != '' %}
                    <div class="swiper-slide">
                        <div class="swiper-slide-item">
                            <img src="{{ i.img_two.url }}">
                        </div>
                    </div>
                    {% endif %}

                    {% if i.img_three != '' %}
                    <div class="swiper-slide">
                        <div class="swiper-slide-item">
                            <img src="{{ i.img_three.url }}">
                        </div>
                    </div>
                    {% endif %}

                    {% if i.img_four != '' %}
                    <div class="swiper-slide">
                        <div class="swiper-slide-item">
                            <img src="{{ i.img_four.url }}">
                        </div>
                    </div>
                    {% endif %}

                    {% if i.img_five != '' %}
                    <div class="swiper-slide">
                        <div class="swiper-slide-item">
                            <img src="{{ i.img_five.url }}">
                        </div>
                    </div>
                    {% endif %}

                    {% if i.img_six != '' %}
                    <div class="swiper-slide">
                        <div class="swiper-slide-item">
                            <img src="{{ i.img_six.url }}">
                        </div>
                    </div>
                    {% endif %}
                </div>
                <!-- If we need pagination -->
                <div class="swiper-pagination"></div>

                <!-- If we need navigation buttons -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>

                <!-- If we need scrollbar -->
                <!-- <div class="swiper-scrollbar"></div> -->
            </div>
        </div>

        <div class="cv-details-info-box">
            <div class="cv-details-customer">{{ i.customer }}</div>
            <h1 class="cv-details-title">
                {{ i.title }}
            </h1>
            <h2 class="cv-details-summery">
                {{ i.body }}
            </h2>
            <h3 class="cv-details-special-options-title">
                فابلیت های ویژه وبسایت :
            </h3>
            <h1 class="cv-details-special-options-text">
                {{ i.details|linebreaks }}
            </h1>
        </div>
    </main>


    {% endfor %}



    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script src="/static/js/navbars.js"></script>
    <script src="/static/js/cv_details.js"></script>
</body>

</html>