aboutus/urls.py
from django.urls import path
from . import views

app_name = 'about-us'
urlpatterns = [
    path('', views.AboutUsView.as_view(), name='about_us')
]

article/urls.py
from django.urls import path
from . import views


app_name = 'article'
urlpatterns = [
    path('', views.ArticleView.as_view(), name='article'),
]

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'
urlpatterns = [
    path('', views.ContactView.as_view(), name='contact'),
]

cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'
urlpatterns = [
    path('', views.CvView.as_view(), name='cv_page'),
    path('cv_details/<int:pk>/', views.CvDetailsView.as_view(), name='cv_details'),
]

hoomanjafari/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='home')),
    path('cv/', include('cv.urls', namespace='cv')),
    path('about-us/', include('aboutus.urls', namespace='about-us')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('article/', include('article.urls', namespace='article')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('search-page/', views.SearchView.as_view(), name='search-page'),
    path('admin_chat_box/', views.AdminChatBox.as_view(), name='admin-chat-box'),
    path('create_connection/', views.creat_connection, name='create-connection'),
    path('create_message/', views.create_message, name='create_message'),
    path('admin_message/', views.admin_message, name='admin-message'),
    path('messages_on_reloading/', views.messages_on_reloading, name='messages-on-reloading'),
    path('check_online_admins/', views.CheckOnlineAdmins.as_view(), name='check-online-admins'),


    path('admin_status_changer/', views.AdminStatusChanger.as_view(), name='admin-status-changer'),
    path('clear_connections_messages/', views.ClearConnectionsMessages.as_view(), name='clear-connections-messages'),
    path('check_user_requests/', views.CheckUserRequests.as_view(), name='check-user-requests'),
    path('create_admin_message/', views.CreateAdminMessage.as_view(), name='create-admin-message'),
    path('show_messages/', views.ShowMessages.as_view(), name='show-messages-inAdminChat'),
    path('user_new_messages/', views.UserNewMessages.as_view(), name='user-new-messages'),
]

templates/includes/footer.html
<footer class="index-footer-container">
    <div class="footer-right-side">
        <div class="footer-about-us">
            <p>مرکزی اراک <i class="fa fa-map-marker"></i></p>
            <p class="me-information-font-e">9372518997 98+ <i class="fa fa-mobile"></i></p>
            <p class="me-information-font-e footer-email-size">hoomanjafari.py@gmail.com <i class="fa fa-envelope"></i></p>
            <a target="_blank" href="https://www.github.com/hoomanjafari">hoomanjafari <i class="fa fa-github"></i></a>
            <ul class="footer-social-media-ul">
                <li><a target="_blank" href="https://www.instagram.com/hooman_jafari76?igsh=MW10bzZoMTVsYzJheA=="><i class="fa fa-instagram"></i></a></li>
                <li><a target="_blank" href="https://t.me/hooman76"><i class="fa fa-telegram"></i></a></li>
                <li><a target="_blank" href="https://www.linkedin.com/in/hooman-jafari-318b69304?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"><i class="fa fa-linkedin"></i></a></li>
            </ul>
        </div>
    </div>

    <div class="footer-middle-side">
        <p>اطلاعات بیشتر</p>
        <ul>
            <li><i class="fa fa-phone"></i><a href="{% url 'contact:contact' %}">تماس با ما</a></li>
            <li><i class="fa fa-question-circle"></i><a href="{% url 'about-us:about_us' %}">درباره ما</a></li>
            <li><i class="fa fa-paperclip"></i><a href="{% url 'cv:cv_page' %}">نمونه کار ها</a></li>
            <li><i class="fa fa-book"></i><a href="{% url 'article:article' %}">بلاگ</a></li>
        </ul>
    </div>

    <div class="footer-left-side">
         تمام تلاش ما در حین انجام پروژه شما کیفیت کار هست، هم از نظر ظاهری شیک و هم از نظر قابلیت های سایت که هم صاحبان مشاغل و هم مشتری هاشون به راحتی از امکانات متنوع سایت استفاده کنن
    </div>
    <div class="site-property">
        <h1>محمد رضا جعفری 1403©</h1>
    </div>
</footer>

templates/includes/live_support.html
<div class="live-support-icon" id="live-support-icon">
    <img alt="live-support-image" src="/static/images/comments.png">
</div>

<section class="live-support-container" id="live-support-container">
    <div class="support-chat-box animate">
        <div class="support-box-header">
            <button class="live-support-close-btn" id="live-support-close-btn"><i class="fa fa-window-close"></i></button>
            <div class="admin-status" id="admin-status">
                <p id="admin-status-p"><span id="admin-status-span"></span> پاسخگوی سوالات شما هست </p>
            </div>
            <div class="support-form" id="support-form">
                <form>
                    {% csrf_token %}
                    <p>* لطفا شماره تماس خود را وارد کنید تا بتوانید از پشتیبانی انلاین استفاده کنید</p>
                    <input id="support-user-name" type="text" placeholder=" ایمیل ...">
                    <input id="support-user-number" type="number" placeholder="شماره تماس ...">
                    <button id="send-user-info" type="button">شروع</button>
                </form>
            </div>
            <div class="indicator" id="indicator">
                <p class="isTyping"><span>هومان</span> is typing</p>
                <span class="indic">
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
            </div>
        </div>
        <div class="support-chatting" id="support-chatting">
            <p class="no-admin-user-msg" id="no-admin-user-msg">لطفا پیام خودتون رو بنویسید زمانی که ادمین انلاین شد جوابتون رو میده</p>
            <div class="admin-message animate" id="admin-1st-message">
                سلام چه کمکی می تونم بهتون بکنم ؟
            </div>
        </div>
        <form class="support-chatting-form" id="support-chatting-form">
            <button id="chat-send-btn" type="button">ارسال</button>
            <textarea class="support-chatting-textarea" id="support-chatting-textarea" rows="1"></textarea>
        </form>
    </div>
</section>

templates/includes/navbar.html
<!-- ----------------------------------( header and navbar's )-------------------------------------------->
<header class="header-main">
    <nav class="header-nav">
        <div class="header-home-logo">
            <a href="{% url 'home:home' %}"><img src="/static/images/home-logo.jpg" alt="home-logo"></a>
        </div>
        <ul class="header-ul" id="header-ul">
            <li><a href="{% url 'about-us:about_us' %}">درباره من</a></li>
            <li><a href="{% url 'cv:cv_page' %}">نمونه کار ها</a></li>
            <li><a href="{% url 'contact:contact' %}">ارتباط با ما</a></li>
            <li><a href="{% url 'article:article' %}">مقالات</a></li>
        </ul>
    </nav>


</header>
<nav class="responsive-fixed-nav">
    <button class="burger_btn" id="burger_btn" type="button"><i class="fa fa-bars"></i></button>
    <a href="{% url 'home:home' %}"><img src="/static/images/home-logo.jpg" alt="logo-image" class="responsive-header-logo-img"></a>
</nav>
<section class="mobile-menu-bar-container" id="mobile-menu-bar-container">
    <div class="mobile-menu-close-btn">
        <button type="button" id="mobile-menu-close-btn">
            <i class="fa fa-window-close" id="window-close"></i>
        </button>
    </div>
    <div class="mobile-menu-bar-box" id="mobile-menu-bar-box">
        <ul class="mobile-menu-bar-ul">
            <li>
                <i class="fa fa-info"></i>
                <a href="{% url 'about-us:about_us' %}">درباره من</a>
            </li>
            <li>
                <i class="fa fa-file"></i>
                <a href="{% url 'cv:cv_page' %}">نمونه کار ها</a>
            </li>
            <li>
                <i class="fa fa-address-book"></i>
                <a href="{% url 'contact:contact' %}">ارتباط با ما</a>
            </li>
            <li>
                <i class="fa fa-book"></i>
                <a href="{% url 'article:article' %}">مقالات</a>
            </li>
        </ul>
    </div>
</section>

templates/includes/search_box.html
<div class="search-box">
    <button class="search-cross" onclick="HiddenSearch()">
        <i class="fa fa-window-close fs-2 text-light"></i>
    </button>
    <div class="search-box-body">
        <h3>متن خود را بنویسید و اینتر کنید</h3>
        <form method="get" action="{% url 'home:search-page' %}">
            {% csrf_token %}
            <input type="search" placeholder="Search ..." class="d-inline-block">
            <button type="submit" class="text-secondary"><i class="fa fa-search fs-1"></i></button>
        </form>
    </div>
</div>

<script>
function HiddenSearch() {
    document.querySelector('.search-box').style.display = 'none'
}
</script>